default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  primary:
    <<: *default
    database: polly_development

  reporting:
    <<: *default
    database: polly_development
